#!/usr/bin/env python3
"""Generate the F-053 package **import map** (not a dataflow map).

Walks ``src/mousedroid/*/``, AST-parses imports (filtering ``TYPE_CHECKING``
blocks), and emits one Markdown file per architectural epic plus an index.
Purpose lines come from each package's ``__init__.py`` module docstring —
packages without one fail closed.

The map states what imports what. In a factory-first DI codebase that is
deliberately *not* the runtime dataflow: ``factory`` fans out and ``config``
fans in because invariants 1-2 require it, and the real seams run through
injected Protocols that AST cannot see. The generated header says so.

Correctness comes from unit tests against a fixture tree and a
regenerate-and-diff regression test — there is no Mermaid renderer in the
toolchain.
"""

from __future__ import annotations

import argparse
import ast
import logging
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - CI always has PyYAML via project deps
    yaml = None  # type: ignore[assignment]

_LOG = logging.getLogger("generate_package_map")

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_SRC = _REPO_ROOT / "src" / "mousedroid"
_DEFAULT_EPICS = Path(__file__).resolve().parent / "package_map_epics.yaml"
_DEFAULT_OUT_DIR = _REPO_ROOT / "docs" / "architecture" / "package-map"
_DEFAULT_INDEX = _REPO_ROOT / "docs" / "architecture" / "package-map.md"

_GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_package_map.py — do not edit by hand. "
    "Run `make package-map` to regenerate. -->"
)

_IMPORT_MAP_DISCLAIMER = """\
> **This is an import map, not a dataflow map.** Edges are `ast`-parsed
> `mousedroid.<package>` imports with `TYPE_CHECKING` blocks filtered out. In a
> factory-first DI codebase the import graph and the runtime seams diverge by
> design: `factory` has many outbound package edges and `config` many inbound
> because architectural invariants 1-2 require it, and the live seams run
> through injected Protocols that `ast` cannot see. Read each section as
> "what imports what", not "what talks to what at runtime".
"""


@dataclass(frozen=True)
class Epic:
    """One architectural epic and the packages it owns."""

    id: str
    title: str
    packages: tuple[str, ...]


@dataclass(frozen=True)
class PackageInfo:
    """Discovered package with purpose line and import neighbours."""

    name: str
    purpose: str
    imports: tuple[str, ...]
    dependents: tuple[str, ...]


def configure_logging(verbose: bool = False) -> None:
    """Pin stdlib logging for CLI use (scripts avoid structlog side-effects)."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(levelname)s %(name)s: %(message)s",
        stream=sys.stderr,
        force=True,
    )


def discover_packages(src_root: Path) -> tuple[str, ...]:
    """Return sorted top-level package names under ``src_root``."""
    if not src_root.is_dir():
        msg = f"package source root does not exist: {src_root}"
        raise FileNotFoundError(msg)
    names = sorted(
        p.name
        for p in src_root.iterdir()
        if p.is_dir() and (p / "__init__.py").is_file() and p.name != "__pycache__"
    )
    if not names:
        msg = f"no packages found under {src_root}"
        raise ValueError(msg)
    return tuple(names)


def load_epics(path: Path, packages: tuple[str, ...]) -> tuple[Epic, ...]:
    """Load the epic roster and fail closed on missing/duplicate packages."""
    if yaml is None:
        msg = "PyYAML is required to load the epic roster"
        raise RuntimeError(msg)
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or "epics" not in raw:
        msg = f"{path}: expected a top-level 'epics' list"
        raise ValueError(msg)
    epics_raw = raw["epics"]
    if not isinstance(epics_raw, list) or not epics_raw:
        msg = f"{path}: 'epics' must be a non-empty list"
        raise ValueError(msg)

    epics: list[Epic] = []
    seen: set[str] = set()
    for entry in epics_raw:
        if not isinstance(entry, dict):
            msg = f"{path}: epic entry must be a mapping"
            raise ValueError(msg)
        epic_id = entry.get("id")
        title = entry.get("title")
        pkgs = entry.get("packages")
        if not isinstance(epic_id, str) or not epic_id.strip():
            msg = f"{path}: epic missing non-empty 'id'"
            raise ValueError(msg)
        if not isinstance(title, str) or not title.strip():
            msg = f"{path}: epic {epic_id!r} missing non-empty 'title'"
            raise ValueError(msg)
        if not isinstance(pkgs, list) or not pkgs:
            msg = f"{path}: epic {epic_id!r} needs a non-empty 'packages' list"
            raise ValueError(msg)
        cleaned: list[str] = []
        for pkg in pkgs:
            if not isinstance(pkg, str) or not pkg.strip():
                msg = f"{path}: epic {epic_id!r} has an empty package name"
                raise ValueError(msg)
            if pkg in seen:
                msg = f"{path}: package {pkg!r} listed in more than one epic"
                raise ValueError(msg)
            seen.add(pkg)
            cleaned.append(pkg)
        epics.append(Epic(id=epic_id.strip(), title=title.strip(), packages=tuple(cleaned)))

    expected = set(packages)
    missing = sorted(expected - seen)
    extra = sorted(seen - expected)
    if missing or extra:
        parts: list[str] = []
        if missing:
            parts.append(f"packages not assigned to any epic: {missing}")
        if extra:
            parts.append(f"epic roster names unknown packages: {extra}")
        raise ValueError("; ".join(parts))
    return tuple(epics)


def purpose_from_init(init_path: Path) -> str:
    """Return the first non-empty docstring line; fail closed if absent."""
    if not init_path.is_file():
        msg = f"missing package __init__.py: {init_path}"
        raise FileNotFoundError(msg)
    source = init_path.read_text(encoding="utf-8")
    if not source.strip():
        msg = f"package __init__.py is empty (no module docstring): {init_path}"
        raise ValueError(msg)
    try:
        tree = ast.parse(source, filename=str(init_path))
    except SyntaxError as exc:
        msg = f"failed to parse {init_path}: {exc}"
        raise ValueError(msg) from exc
    doc = ast.get_docstring(tree)
    if doc is None or not doc.strip():
        msg = f"package __init__.py has no module docstring: {init_path}"
        raise ValueError(msg)
    for line in doc.strip().splitlines():
        cleaned = line.strip()
        if cleaned:
            return cleaned
    msg = f"package __init__.py docstring is blank: {init_path}"
    raise ValueError(msg)


def _is_type_checking_test(node: ast.AST) -> bool:
    """True when ``node`` is the test of ``if TYPE_CHECKING`` / ``typing.TYPE_CHECKING``."""
    if isinstance(node, ast.Name) and node.id == "TYPE_CHECKING":
        return True
    return (
        isinstance(node, ast.Attribute)
        and node.attr == "TYPE_CHECKING"
        and isinstance(node.value, ast.Name)
        and node.value.id == "typing"
    )


def _target_package(module: str | None, packages: frozenset[str]) -> str | None:
    """Map ``mousedroid.<pkg>...`` to ``<pkg>`` when ``<pkg>`` is a known package."""
    if not module:
        return None
    parts = module.split(".")
    if len(parts) < 2 or parts[0] != "mousedroid":
        return None
    candidate = parts[1]
    if candidate in packages:
        return candidate
    return None


def collect_import_edges(src_root: Path, packages: tuple[str, ...]) -> dict[str, set[str]]:
    """Build ``{pkg: set(imported_pkgs)}`` from non-``TYPE_CHECKING`` imports."""
    package_set = frozenset(packages)
    edges: dict[str, set[str]] = {name: set() for name in packages}

    def visit(node: ast.AST, owner: str, in_type_checking: bool) -> None:
        if isinstance(node, ast.If) and _is_type_checking_test(node.test):
            for child in node.body:
                visit(child, owner, True)
            for child in node.orelse:
                visit(child, owner, in_type_checking)
            return
        if not in_type_checking:
            if isinstance(node, ast.ImportFrom):
                target = _target_package(node.module, package_set)
                if target is not None and target != owner:
                    edges[owner].add(target)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    target = _target_package(alias.name, package_set)
                    if target is not None and target != owner:
                        edges[owner].add(target)
        # Nested function/class bodies still count: a deferred import is a real
        # runtime dependency even when it is not a module-level edge.
        # TYPE_CHECKING is the only filter this map applies.
        for child in ast.iter_child_nodes(node):
            visit(child, owner, in_type_checking)

    for name in packages:
        for path in sorted((src_root / name).rglob("*.py")):
            if path.name == "__pycache__":
                continue
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            except (OSError, SyntaxError) as exc:
                _LOG.warning("skipping unreadable/unparseable file %s: %s", path, exc)
                continue
            visit(tree, name, False)
    return edges


def build_package_infos(
    src_root: Path, packages: tuple[str, ...], edges: dict[str, set[str]]
) -> dict[str, PackageInfo]:
    """Attach purpose lines and sorted import/dependent lists."""
    dependents: dict[str, set[str]] = defaultdict(set)
    for src, targets in edges.items():
        for dst in targets:
            dependents[dst].add(src)

    infos: dict[str, PackageInfo] = {}
    for name in packages:
        purpose = purpose_from_init(src_root / name / "__init__.py")
        imports = tuple(sorted(edges.get(name, ())))
        deps = tuple(sorted(dependents.get(name, ())))
        infos[name] = PackageInfo(name=name, purpose=purpose, imports=imports, dependents=deps)
    return infos


def _mermaid_subgraph(info: PackageInfo) -> str:
    """Render a small LR graph of this package's import neighbourhood."""
    lines = ["```mermaid", "graph LR", f"  {info.name}[{info.name}]"]
    for target in info.imports:
        lines.append(f"  {info.name} --> {target}")
    for source in info.dependents:
        lines.append(f"  {source} --> {info.name}")
    lines.append("```")
    return "\n".join(lines)


def render_package_section(info: PackageInfo) -> str:
    """One Markdown section for a single package."""
    imports = ", ".join(f"`{p}`" for p in info.imports) if info.imports else "*(none)*"
    dependents = ", ".join(f"`{p}`" for p in info.dependents) if info.dependents else "*(none)*"
    return "\n".join(
        [
            f"## `{info.name}`",
            "",
            f"**Purpose:** {info.purpose}",
            "",
            f"**Imports:** {imports}",
            "",
            f"**Dependents:** {dependents}",
            "",
            _mermaid_subgraph(info),
            "",
        ]
    )


def render_epic_document(
    epic: Epic, infos: dict[str, PackageInfo], *, relative_index: str = "../package-map.md"
) -> str:
    """Full Markdown body for one epic file."""
    parts = [
        _GENERATED_BANNER,
        "",
        f"# Package import map — {epic.title}",
        "",
        _IMPORT_MAP_DISCLAIMER,
        "",
        f"Epic id: `{epic.id}`. Index: [`package-map.md`]({relative_index}).",
        "",
    ]
    for name in epic.packages:
        parts.append(render_package_section(infos[name]))
    return "\n".join(parts).rstrip() + "\n"


def render_index(epics: tuple[Epic, ...], infos: dict[str, PackageInfo]) -> str:
    """Top-level index linking every epic file and summarising coverage."""
    edge_count = sum(len(info.imports) for info in infos.values())
    parts = [
        _GENERATED_BANNER,
        "",
        "# Package import map",
        "",
        _IMPORT_MAP_DISCLAIMER,
        "",
        f"Covers **{len(infos)}** packages and **{edge_count}** directed package-level "
        "import edges, split per architectural epic:",
        "",
    ]
    for epic in epics:
        rel = f"package-map/{epic.id}.md"
        parts.append(f"- [{epic.title}]({rel}) (`{epic.id}`) — {len(epic.packages)} packages")
    parts.append("")
    parts.append("## Packages by epic")
    parts.append("")
    for epic in epics:
        parts.append(f"### {epic.title}")
        parts.append("")
        for name in epic.packages:
            purpose = infos[name].purpose
            parts.append(f"- [`{name}`](package-map/{epic.id}.md#{name}) — {purpose}")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def normalize_for_compare(text: str) -> str:
    """Normalise line endings and path separators for Windows-safe diffs."""
    return text.replace("\r\n", "\n").replace("\r", "\n").replace("\\", "/")


def generate(
    *,
    src_root: Path,
    epics_path: Path,
    out_dir: Path,
    index_path: Path,
) -> dict[Path, str]:
    """Return ``{absolute_path: content}`` for the index and every epic file."""
    packages = discover_packages(src_root)
    epics = load_epics(epics_path, packages)
    edges = collect_import_edges(src_root, packages)
    infos = build_package_infos(src_root, packages, edges)
    outputs: dict[Path, str] = {
        index_path.resolve(): render_index(epics, infos),
    }
    for epic in epics:
        path = (out_dir / f"{epic.id}.md").resolve()
        outputs[path] = render_epic_document(epic, infos)
    return outputs


def write_outputs(outputs: dict[Path, str]) -> None:
    """Persist generated files, creating parent directories as needed."""
    for path, content in sorted(outputs.items(), key=lambda item: str(item[0])):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        _LOG.info("wrote %s (%d bytes)", path, len(content.encode("utf-8")))


def check_outputs(outputs: dict[Path, str]) -> list[str]:
    """Return human-readable drift messages; empty means the tree matches."""
    problems: list[str] = []
    for path, expected in sorted(outputs.items(), key=lambda item: str(item[0])):
        if not path.is_file():
            problems.append(f"missing generated file: {path}")
            continue
        actual = path.read_text(encoding="utf-8")
        if normalize_for_compare(actual) != normalize_for_compare(expected):
            problems.append(f"stale generated file: {path}")
    # Extra files under out_dir that we did not produce would mean a removed
    # epic left an orphan — flag any *.md beside the expected set.
    if outputs:
        out_dirs = {path.parent for path in outputs}
        expected_names = {path.name for path in outputs}
        for directory in out_dirs:
            if not directory.is_dir():
                continue
            # Only scan the package-map/ subdirectory for orphans, not the
            # parent docs/architecture/ which holds many hand-written files.
            if directory.name != "package-map":
                continue
            for child in directory.glob("*.md"):
                if child.name not in expected_names:
                    problems.append(f"orphan generated file (not in epic roster): {child}")
    return problems


def build_parser() -> argparse.ArgumentParser:
    """CLI parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src-root",
        type=Path,
        default=_DEFAULT_SRC,
        help="Top-level package directory (default: src/mousedroid)",
    )
    parser.add_argument(
        "--epics",
        type=Path,
        default=_DEFAULT_EPICS,
        help="Epic roster YAML (default: scripts/package_map_epics.yaml)",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=_DEFAULT_OUT_DIR,
        help="Directory for per-epic Markdown files",
    )
    parser.add_argument(
        "--index",
        type=Path,
        default=_DEFAULT_INDEX,
        help="Path of the generated index Markdown file",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if committed outputs differ from a fresh generation",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Debug logging")
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry — returns the process exit code."""
    args = build_parser().parse_args(argv)
    configure_logging(verbose=args.verbose)
    try:
        outputs = generate(
            src_root=args.src_root,
            epics_path=args.epics,
            out_dir=args.out_dir,
            index_path=args.index,
        )
    except (OSError, ValueError, RuntimeError) as exc:
        _LOG.error("%s", exc)
        return 2

    if args.check:
        problems = check_outputs(outputs)
        if problems:
            for problem in problems:
                _LOG.error("%s", problem)
            _LOG.error("re-run `make package-map` and commit the result")
            return 1
        _LOG.info("package import map is up to date (%d files)", len(outputs))
        return 0

    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
