#!/usr/bin/env bash
# =============================================================================
# probe_devices.sh — Generate docker-compose.devices.yml with present devices
# =============================================================================
# Usage: bash scripts/probe_devices.sh > docker-compose.devices.yml
#
# Probes for known MouseDroid hardware devices and outputs a Docker Compose
# override file containing only the devices that physically exist on the host.
# =============================================================================

set -euo pipefail

DEVICES=()
GROUPS=()

# ESP32 UART serial
if [ -e /dev/ttyUSB0 ]; then
    DEVICES+=("      - /dev/ttyUSB0:/dev/ttyUSB0")
    echo "INFO: ESP32 found at /dev/ttyUSB0" >&2
else
    echo "WARN: ESP32 not found at /dev/ttyUSB0" >&2
fi

# FHL-LD19 LiDAR UART
if [ -e /dev/ttyUSB1 ]; then
    DEVICES+=("      - /dev/ttyUSB1:/dev/ttyUSB1")
    echo "INFO: LiDAR found at /dev/ttyUSB1" >&2
else
    echo "WARN: LiDAR not found at /dev/ttyUSB1" >&2
fi

# CSI Camera
if [ -e /dev/video0 ]; then
    DEVICES+=("      - /dev/video0:/dev/video0")
    echo "INFO: Camera found at /dev/video0" >&2
else
    echo "WARN: Camera not found at /dev/video0" >&2
fi

# Wonrabai USB Sound Card (ALSA)
if [ -d /dev/snd ]; then
    DEVICES+=("      - /dev/snd:/dev/snd")
    GROUPS+=("      - audio")
    echo "INFO: ALSA audio found at /dev/snd" >&2
else
    echo "WARN: ALSA audio not found at /dev/snd" >&2
fi

# GPIO (for ultrasonic — not currently installed)
if [ -e /dev/gpiochip0 ]; then
    DEVICES+=("      - /dev/gpiochip0:/dev/gpiochip0")
    echo "INFO: GPIO chip0 found" >&2
fi
if [ -e /dev/gpiochip1 ]; then
    DEVICES+=("      - /dev/gpiochip1:/dev/gpiochip1")
    echo "INFO: GPIO chip1 found" >&2
fi

# Output the override YAML
echo "# Auto-generated by probe_devices.sh — do not edit"
echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "services:"
echo "  mousedroid:"

if [ ${#DEVICES[@]} -gt 0 ]; then
    echo "    devices:"
    for dev in "${DEVICES[@]}"; do
        echo "$dev"
    done
fi

if [ ${#GROUPS[@]} -gt 0 ]; then
    echo "    group_add:"
    for grp in "${GROUPS[@]}"; do
        echo "$grp"
    done
fi

echo ""
echo "INFO: ${#DEVICES[@]} device(s) found" >&2
